# Generated by Django 3.2 on 2024-10-09 07:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_remove_user_unique_email_username'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
