ERROR_MISSING_TOKENS = (
    'Отсутствуют необходимые переменные окружения. '
    'Проверьте наличие {missing_tokens}.'
)
BOT_OK = 'Бот отправил сообщение\n{}'
BOT_ERROR = 'Ошибка телеграм бота\n{}'
API_ERROR = 'Код ответа Api {}'
API_ERROR1 = 'Ошибка при запросе к API \nurl={}, headers={}, params={}.\n{}'
API_ERROR2 = 'В ответе сервера нет значения homework_name.'
JSON_ERROR = 'Не соответствуют JSON-формату \n{}'
NO_DICT = 'Ответ сервера, не является словарем {}'
NO_LIST = 'Ответ сервера, homeworks не является списком {}'
NO_INFO = 'В ответе сервера нет информации.'
STATUS_MESSAGE = 'Изменился статус проверки работы "{}". {}'
NOT_STATUS = 'Статус не определен'
STATUS_CHANGED = 'Статус изменился.'
ERROR_MESSAGE = 'Сбой в работе программы: {}'
