# Generated by Django 3.2.16 on 2024-09-12 18:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0012_auto_20240912_1807'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='follow',
            name='unique_name_follower',
        ),
    ]
