# Generated by Django 3.2.16 on 2024-09-14 12:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0016_follow_unique_name_follower'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='follow',
            options={'ordering': ('user',), 'verbose_name': 'Подписка', 'verbose_name_plural': 'Подписки'},
        ),
    ]
